# Version of the Icarus theme that is currently used
version: 2.3.0
# Path or URL to the website's icon
favicon: /images/tbf-icon.svg
# Path or URL to RSS atom.xml
rss: /atom.xml
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
logo:
    text: æŠ€è¡“æ›¸å…¸å…¬å¼ãƒ–ãƒ­ã‚°
# Open Graph metadata
# https://hexo.io/docs/helpers.html#open-graph
open_graph:
    # Facebook App ID
    # fb_app_id: 
    # Facebook Admin ID
    # fb_admins: 
    # Twitter ID
    twitter_id: techbookfest
    # Twitter site
    twitter_site: https://techbookfest.org/
    # Google+ profile link
    # google_plus: 
# Navigation bar link settings
navbar:
    # Navigation bar menu links
    menu:
        # Home: /
        Archives: /archives
        ã‚µãƒ¼ã‚¯ãƒ«å‚åŠ ğŸ˜º: https://techbookfest.org/event/tbf15#requirements
        æŠ€è¡“æ›¸å…¸15ï¼ˆã‚ªãƒ³ãƒ©ã‚¤ãƒ³ï¼š11/11-11/26ã€ã‚ªãƒ•ãƒ©ã‚¤ãƒ³ï¼š11/12ï¼‰: https://techbookfest.org/event/tbf15
        # Categories: /categories
        # Tags: /tags
        # About: /about
    # Navigation bar links to be shown on the right
    links:
        # å…¬å¼ã‚µã‚¤ãƒˆ: https://techbookfest.org/
        # Download on GitHub:
        #     icon: fab fa-github
        #     url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Footer section link settings
footer:
    # Links to be shown on the right of the footer section
    links:
        # Creative Commons:
        #     icon: fab fa-creative-commons
        #     url: 'https://creativecommons.org/'
        # Attribution 4.0 International:
        #     icon: fab fa-creative-commons-by
        #     url: 'https://creativecommons.org/licenses/by/4.0/'
        # Download on GitHub:
        #     icon: fab fa-github
        #     url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Article display settings
article:
    # Code highlight theme
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    highlight: atom-one-light
    # Whether to show article thumbnail images
    thumbnail: false
    # Whether to show estimate article reading time
    readtime: false
# Search plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search
search:
    # Name of the search plugin
    type: insight
# Comment plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment
comment:
    # Name of the comment plugin
    type: 
# Donation entries
# https://ppoffice.github.io/hexo-theme-icarus/categories/Donation/
donate:
    # -
    #     # Donation entry name
    #     type: alipay
    #     # Qrcode image URL
    #     qrcode: ''
    # -
    #     # Donation entry name
    #     type: wechat
    #     # Qrcode image URL
    #     qrcode: ''
    # -
    #     # Donation entry name
    #     type: paypal
    #     # Paypal business ID or email address
    #     business: ''
    #     # Currency code
    #     currency_code: USD
    # -
    #     # Donation entry name
    #     type: patreon
    #     # URL to the Patreon page
    #     url: ''
# Share plugin settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share
share:
    # Share plugin name
    type: 
# Sidebar settings.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # left sidebar settings
    left:
        # Whether the left sidebar is sticky when page scrolls
        # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
    # right sidebar settings
    right:
        # Whether the right sidebar is sticky when page scrolls
        # https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
# Sidebar widget settings
# https://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    -
        # Widget name
        type: profile
        # Where should the widget be placed, left or right
        position: left
        # Author name to be shown in the profile widget
        author: æŠ€è¡“æ›¸å…¸
        # Title of the author to be shown in the profile widget
        author_title: é‹å–¶äº‹å‹™å±€
        # Author's current location to be shown in the profile widget
        location: 5/20-6/4 ã‚ªãƒ³ãƒ©ã‚¤ãƒ³ã€5/21 ã‚ªãƒ•ãƒ©ã‚¤ãƒ³
        # Path or URL to the avatar to be shown in the profile widget
        avatar: /css/images/tbf-icon.svg
        # Email address for the Gravatar to be shown in the profile widget
        # gravatar: 
        # Whether to show avatar image rounded or square
        avatar_rounded: false
        # Path or URL for the follow button
        follow_link: 'https://twitter.com/techbookfest/'
        # Links to be shown on the bottom of the profile widget
        social_links:
            # Github:
            #     icon: fab fa-github
            #     url: 'https://github.com/ppoffice'
            # Facebook:
            #     icon: fab fa-facebook
            #     url: 'https://facebook.com'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com/techbookfest'
            # Dribbble:
            #     icon: fab fa-dribbble
            #     url: 'https://dribbble.com'
            RSS:
                icon: fas fa-rss
                url: /
    -
        # Widget name
        type: toc
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: links
        # Where should the widget be placed, left or right
        position: left
        # Links to be shown in the links widget
        links:
            å…¬å¼ã‚µã‚¤ãƒˆ: https://techbookfest.org/            
            æŠ€è¡“æ›¸å…¸14: https://techbookfest.org/event/tbf14
            æŠ€è¡“æ›¸å…¸13: https://techbookfest.org/event/tbf13
            æŠ€è¡“æ›¸å…¸12: https://techbookfest.org/event/tbf12
            æŠ€è¡“æ›¸å…¸11: https://techbookfest.org/event/tbf11
            æŠ€è¡“æ›¸å…¸10: https://techbookfest.org/event/tbf10
            æŠ€è¡“æ›¸å…¸9: https://techbookfest.org/event/tbf09
            æŠ€è¡“æ›¸å…¸8: https://techbookfest.org/event/tbf08
            æŠ€è¡“æ›¸å…¸7: https://techbookfest.org/event/tbf07
            æŠ€è¡“æ›¸å…¸6: https://techbookfest.org/event/tbf06
            æŠ€è¡“æ›¸å…¸5: https://techbookfest.org/event/tbf05
            æŠ€è¡“æ›¸å…¸4: https://techbookfest.org/event/tbf04
            æŠ€è¡“æ›¸å…¸3: https://techbookfest.org/event/tbf03
            è¶…æŠ€è¡“æ›¸å…¸: https://techbookfest.org/event/cho01
            æŠ€è¡“æ›¸å…¸2: https://techbookfest.org/event/tbf02
            æŠ€è¡“æ›¸å…¸: https://techbookfest.org/tbf01
    # -
    #     # Widget name
    #     type: category
    #     # Where should the widget be placed, left or right
    #     position: left
    -
        # Widget name
        type: tagcloud
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: recent_posts
        # Where should the widget be placed, left or right
        position: right
    -
        # Widget name
        type: tag
        # Where should the widget be placed, left or right
        position: right
    -
        # Widget name
        type: archive
        # Where should the widget be placed, left or right
        position: right
# Other plugin settings
plugins:
    # Enable page animations
    animejs: false
    # Enable the lightGallery and Justified Gallery plugins
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
    gallery: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated-browser: true
    # Enable the MathJax plugin
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/mathjax-plugin/
    mathjax: true
    # Show the back to top button on mobile devices
    back-to-top: true
    # Google Analytics plugin settings
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Google-Analytics
    google-analytics:
        # Google Analytics tracking id
        tracking_id: UA-75502922-3
    # Baidu Analytics plugin settings
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Baidu-Analytics
    # baidu-analytics:
    #     # Baidu Analytics tracking id
    #     tracking_id: 
    # Hotjar user feedback plugin
    # https://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Hotjar
    # hotjar:
    #     # Hotjar site id
    #     site_id: 
    # Show a loading progress bar at top of the page
    progressbar: true
    # Show the copy button in the highlighted code area
    # clipboard: true
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    # busuanzi: false
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL of the webfont CDN provider
    fontcdn: google
    # Name or URL of the webfont Icon CDN provider
    iconcdn: fontawesome
