# Menus
menu:
  # Blog: .
  Archives: archives
  # Official: https://techbookfest.org/
  ã‚µãƒ¼ã‚¯ãƒ«å‚åŠ ğŸ˜º: https://techbookfest.org/event/tbf06#requirements
  æŠ€è¡“æ›¸å…¸6 4/14: https://techbookfest.org/event/tbf06
  # Categories: categories
  # Tags: tags
  # About: about

# Customize
customize:
    logo:
        enabled: false
        width: 40
        height: 40
        url: images/tbf-icon.svg
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/tbf-icon.svg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: æŠ€è¡“æ›¸å…¸
        author_title: æŠ€è¡“æ›¸ã®ãŠç¥­ã‚Šï¼
        location: 4/14 ã‚µãƒ³ã‚·ãƒ£ã‚¤ãƒ³ã‚·ãƒ†ã‚£ æ–‡åŒ–ä¼šé¤¨ãƒ“ãƒ«2F å±•ç¤ºãƒ›ãƒ¼ãƒ«D
        follow: https://twitter.com/techbookfest/
    highlight: monokai
    sidebar: right # sidebar position, options: left, right or leave it empty
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: css/images/favicon.ico
    social_links:
        # github: http://github.com/ppoffice/hexo-theme-icarus
        twitter: https://twitter.com/techbookfest/
        # facebook: /
        # dribbble: /
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan: # please fill in `appid` and `conf` to enable
        appid:
        conf:
    gitment:
        owner: #your github ID
        repo: #the repo to store comments
        #Register an OAuth application, and you will get a client ID and a client secret.
        client_id: #your client ID
        client_secret: #your client secret

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: false # options: true, false
    justifiedgallery: false # options: true, false
    google_analytics: UA-75502922-3
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key
    mathjax: false # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id: techbookfest
        google_plus:
    links:
        å…¬å¼ã‚µã‚¤ãƒˆ: https://techbookfest.org/
        æŠ€è¡“æ›¸å…¸6: https://techbookfest.org/event/tbf06
        æŠ€è¡“æ›¸å…¸5: https://techbookfest.org/event/tbf05
        æŠ€è¡“æ›¸å…¸4: https://techbookfest.org/event/tbf04
        æŠ€è¡“æ›¸å…¸3: https://techbookfest.org/event/tbf03
        è¶…æŠ€è¡“æ›¸å…¸: https://techbookfest.org/event/cho01
        æŠ€è¡“æ›¸å…¸2: https://techbookfest.org/event/tbf02
        æŠ€è¡“æ›¸å…¸: https://techbookfest.org/tbf01
